### ISSUE TITLE
Can't retrieve response

### ISSUE THREAD

**Issue by FloLaco** [tbotnz/netpalm#193]
On fresh deployment using : `./redis_gen_new_certs.sh && docker-compose up -d --build`

1. Create a getconfig task : 
```
POST /getconfig HTTP/1.1
Host: xxxx.com:9000
x-api-key: xxxxx
Content-Type: application/json
Content-Length: 360

{
    "library": "netmiko",
    "connection_args": {
        "device_type": "cisco_ios",
        "host": "10.x.x.x",
        "username": "florian_lacommare",
        "password": "xxxxx."
    },
    "command": "show ip int brief",
    "args": {
        "use_textfsm": true
    },
    "queue_strategy": "fifo"
}
```
Response : 
```
{
    "status": "success",
    "data": {
        "task_id": "90ddad9d-f169-43a6-8a70-b6120ce8570a",
        "created_on": "2022-09-30 06:19:57.094087",
        "task_queue": "fifo",
        "task_meta": {
            "enqueued_at": "2022-09-30 06:19:57.094526",
            "started_at": null,
            "ended_at": null,
            "enqueued_elapsed_seconds": "0",
            "total_elapsed_seconds": "0",
            "assigned_worker": null
        },
        "task_status": "queued",
        "task_result": null,
        "task_errors": []
    }
}
```

Log on controler : 
```
[2022-09-30 06:19:57,090:netpalm.routers.route_utils:wrapper:DEBUG] cacheable_model: req_data {'library': <LibraryName.netmiko: 'netmiko'>, 'connection_args': {'device_type': 'cisco_ios', 'host': '10.x.x.x', 'username': 'florian_lacommare', 'password': '******'}, 'command': 'show ip int brief', 'args': {'use_textfsm': True}, 'webhook': {}, 'queue_strategy': <QueueStrategy.fifo: 'fifo'>, 'post_checks': [], 'cache': {}, 'ttl': None}
[2022-09-30 06:19:57,091:netpalm.routers.route_utils:cache_key_from_req_data:INFO] hashed key: add992c10c403a5fde3f95b9e9a45c32040445bbcfd572382dbb1c91271093d6
[2022-09-30 06:19:57,091:netpalm.routers.route_utils:cache_key_from_req_data:DEBUG] cache_key_from_req_data: cache key 10.x.x.x:None:show ip int brief:add992c10c403a5fde3f95b9e9a45c32040445bbcfd572382dbb1c91271093d6
[2022-09-30 06:19:57,093:netpalm.backend.core.redis.rediz:__sendtask:DEBUG] __sendtask: {'library': <LibraryName.netmiko: 'netmiko'>, 'connection_args': {'device_type': 'cisco_ios', 'host': '10.x.x.x', 'username': 'florian_lacommare', 'password': '******'}, 'command': 'show ip int brief', 'args': {'use_textfsm': True}, 'webhook': {}, 'queue_strategy': <QueueStrategy.fifo: 'fifo'>, 'post_checks': [], 'cache': {}}
```

2. Get task info for `90ddad9d-f169-43a6-8a70-b6120ce8570a`
```
GET /task/90ddad9d-f169-43a6-8a70-b6120ce8570a HTTP/1.1
Host: xxxx.com:9000
x-api-key: xxxx
Content-Type: application/json
```

Response : 
```
{
    "detail": "Not Found"
}
```

log controller : 
```
[2022-09-30 06:22:06,565:netpalm.backend.core.redis.rediz:fetchtask:INFO] fetching task: 90ddad9d-f169-43a6-8a70-b6120ce8570a
```

3. That's it ... no info, no task ...

For info, my task failed but I still should get task info which tell me that my task failed, right ? : 
```
[2022-09-30 06:19:57,100:rq.worker:dequeue_job_and_maintain_ttl:INFO] fifo: fifo (90ddad9d-f169-43a6-8a70-b6120ce8570a)
[2022-09-30 06:19:57,130:netpalm.backend.core.utilities.rediz_meta:write_meta_error:ERROR] `write_meta_error` processing error
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 920, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.8/site-packages/paramiko/client.py", line 368, in connect
    raise NoValidConnectionsError(errors)
paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on 10.x.x.x

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/netpalm/backend/plugins/drivers/netmiko/netmiko_drvr.py", line 27, in connect
    netmikoses = ConnectHandler(**self.connection_args)
  File "/usr/local/lib/python3.8/site-packages/netmiko/ssh_dispatcher.py", line 312, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/netmiko/cisco/cisco_ios.py", line 17, in __init__
    return super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 346, in __init__
    self._open()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 351, in _open
    self.establish_connection()
  File "/usr/local/lib/python3.8/site-packages/netmiko/base_connection.py", line 942, in establish_connection
    raise NetmikoTimeoutException(msg)
netmiko.ssh_exception.NetmikoTimeoutException: TCP connection to device failed.

Common causes of this problem are:
1. Incorrect hostname or IP address.
2. Wrong TCP port.
3. Intermediate firewall blocking access.

Device settings: cisco_ios 10.x.x.x:22


[2022-09-30 06:19:57,134:rq.worker:handle_exception:ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 1075, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 854, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 877, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/code/netpalm/backend/plugins/calls/getconfig/exec_command.py", line 111, in exec_command
    write_meta_error(e)
  File "/code/netpalm/backend/core/utilities/rediz_meta.py", line 32, in write_meta_error
    raise exception from None  # Don't process the same exception twice
  File "/code/netpalm/backend/plugins/calls/getconfig/exec_command.py", line 36, in exec_command
    sesh = netmik.connect()
  File "/code/netpalm/backend/plugins/drivers/netmiko/netmiko_drvr.py", line 30, in connect
    write_meta_error(e)
  File "/code/netpalm/backend/core/utilities/rediz_meta.py", line 49, in write_meta_error
    raise NetpalmMetaProcessedException from exception
netpalm.exceptions.NetpalmMetaProcessedException
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rq/worker.py", line 1075, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 854, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.8/site-packages/rq/job.py", line 877, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/code/netpalm/backend/plugins/calls/getconfig/exec_command.py", line 111, in exec_command
    write_meta_error(e)
  File "/code/netpalm/backend/core/utilities/rediz_meta.py", line 32, in write_meta_error
    raise exception from None  # Don't process the same exception twice
  File "/code/netpalm/backend/plugins/calls/getconfig/exec_command.py", line 36, in exec_command
    sesh = netmik.connect()
  File "/code/netpalm/backend/plugins/drivers/netmiko/netmiko_drvr.py", line 30, in connect
    write_meta_error(e)
  File "/code/netpalm/backend/core/utilities/rediz_meta.py", line 49, in write_meta_error
    raise NetpalmMetaProcessedException from exception
netpalm.exceptions.NetpalmMetaProcessedException
```

**Comment by hanunes** [comment]
Hi, I've seen this happen before, where for some reason a you don't get assigned an `"assigned_worker": null`.

From my experience, bringing all of the netpalm controller and workers down, and bringing them back up solved it (using docker).

`docker-compose down`
`docker-compose up -d --build`

**Comment by FloLaco** [comment]
I did not fix the issue, but when my task is a success (meaning That I provide a good IP address) there is no issue. If I provide a wrong IP, the issue is happening
